spring:
  jpa:
    show-sql: true
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:db-commandes;
      username: sa
      password:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
mes-configs:
  limitDeCommandes: 10
server:
  port: 9002
